### PR TITLE
CoffeeScript -> JS

### PR DESCRIPTION
**Pull request by TimvdLippe**
This PR updates all coffeescript files to JS ES6 to be compatible with Hubot 3.

### CODE REVIEW

**Comment by wbrbr** [comment]
:+1: just needs to fix some stuff before publishing to NPM

**Comment by wbrbr** [comment]
Can you confirm that it works now ? :)

**Comment by TimvdLippe** [comment]
I can test it tomorrow 😄

**Comment by TimvdLippe** [comment]
It works, thanks!

Op ma 4 dec. 2017 om 20:04 schreef Wilhem Barbier <notifications@github.com

**Pull request merged**
